package dungeonescape.helper;

public class TileDecider {

	public static String isGround(int code) {
		switch (code) {
		case Tile.GROUND_LAVA:
		case Tile.GROUND_DARK:
		case Tile.GROUND_STONE:
		case Tile.GROUND_STONE_BROKEN:
			return Tile.GROUND_IMG_PATH + code;
		case Tile.INTERIOR_TRAP_DOOR:
			return Tile.INTERIOR_IMG_PATH + code;
		case Tile.OUTDOORS_GRASS:
		case Tile.OUTDOORS_GRASS1:
		case Tile.OUTDOORS_COBBLESTONE:
		case Tile.OUTDOORS_COBBLESTONE_TOP_LEFT:
		case Tile.OUTDOORS_COBBLESTONE_MIDDLE_LEFT:
		case Tile.OUTDOORS_COBBLESTONE_BOTTOM_LEFT:
		case Tile.OUTDOORS_COBBLESTONE_BOTTOM_MIDDLE:
		case Tile.OUTDOORS_COBBLESTONE_BOTTOM_RIGHT:
		case Tile.OUTDOORS_COBBLESTONE_MIDDLE_RIGHT:
		case Tile.OUTDOORS_COBBLESTONE_TOP_RIGHT:
		case Tile.OUTDOORS_COBBLESTONE_TOP_MIDDLE:
		case Tile.OUTDOORS_COBBLESTONE_INSIDE_TOP_RIGHT:
		case Tile.OUTDOORS_COBBLESTONE_INSIDE_TOP_LEFT:
		case Tile.OUTDOORS_COBBLESTONE_INSIDE_BOTTOM_RIGHT:
		case Tile.OUTDOORS_COBBLESTONE_INSIDE_BOTTOM_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU:
		case Tile.OUTDOORS_STONE_PLATEAU_TOP_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_MIDDLE_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_BOTTOM_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_BOTTOM_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_BOTTOM_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_MIDDLE_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_TOP_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_TOP_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_INSIDE_TOP_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_INSIDE_TOP_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_INSIDE_BOTTOM_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_INSIDE_BOTTOM_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_NORTH:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_NORTH_END:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_WEST:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_WEST_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_WEST_END:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_SOUTH:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_SOUTH_END:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_EAST:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_EAST_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_EAST_END:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_RIGHT:
			return Tile.OUTDOORS_IMG_PATH + code;
		default:
			return "";
		}
	}

	public static String isCollision(int code) {
		switch (code) {
		case Tile.WALL_CAVE_BOTTOM:
		case Tile.WALL_CAVE_BOTTOM_CRACK:
		case Tile.WALL_CAVE_BOTTOM_DARK:
		case Tile.WALL_CAVE_TOP:
		case Tile.WALL_CAVE_MIDDLE:
		case Tile.WALL_STONE:
		case Tile.WALL_STONE_CRACK:
		case Tile.WALL_STONE_BLOCK_LOWER:
		case Tile.WALL_STONE_BLOCK_UPPER:
		case Tile.WALL_CAVE_DOOR_BOTTOM:
		case Tile.WALL_CAVE_DOOR_LEFT:
		case Tile.WALL_CAVE_DOOR_RIGHT:
		case Tile.WALL_CAVE_DOOR_LEFT_UPPER:
		case Tile.WALL_CAVE_DOOR_RIGHT_UPPER:
		case Tile.WALL_CAVE_DOOR_LOWER:
		case Tile.WALL_CAVE_DOOR_UPPER:
		case Tile.WALL_LAVA_LEFT_LOW:
		case Tile.WALL_LAVA_LEFT_LOWER:
		case Tile.WALL_LAVA_LEFT_LOWEST:
		case Tile.WALL_LAVA_LEFT_MIDDLE:
		case Tile.WALL_LAVA_LEFT_UPPER:
		case Tile.WALL_LAVA_RIGHT_LOW:
		case Tile.WALL_LAVA_RIGHT_LOWER:
		case Tile.WALL_LAVA_RIGHT_LOWEST:
		case Tile.WALL_LAVA_RIGHT_MIDDLE:
		case Tile.WALL_LAVA_RIGHT_UPPER:
		case Tile.WALL_LAVA_LOW:
		case Tile.WALL_LAVA_LOWER:
		case Tile.WALL_LAVA_LOWEST:
		case Tile.WALL_LAVA_UPPER:
			return Tile.WALL_IMG_PATH + code;
		case Tile.OUTDOORS_FENCE_ALONE:
		case Tile.OUTDOORS_FENCE_END:
		case Tile.OUTDOORS_FENCE_CROSS:
		case Tile.OUTDOORS_FENCE_TOP_LEFT:
		case Tile.OUTDOORS_FENCE_TOP_RIGHT:
		case Tile.OUTDOORS_FENCE_BOTTOM_LEFT:
		case Tile.OUTDOORS_FENCE_BOTTOM_RIGHT:
		case Tile.OUTDOORS_FENCE_HORIZONTAL:
		case Tile.OUTDOORS_FENCE_VERTICAL:
		case Tile.OUTDOORS_FENCE_CROSS_LEFT:
		case Tile.OUTDOORS_FENCE_CROSS_RIGHT:
		case Tile.OUTDOORS_FENCE_CROSS_NORTH:
		case Tile.OUTDOORS_FENCE_CROSS_SOUTH:
		case Tile.OUTDOORS_FENCE_TOP_LEFT1:
		case Tile.OUTDOORS_FENCE_TOP_RIGHT1:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_RIGHT:
			return Tile.OUTDOORS_IMG_PATH + code;
		default:
			return "";
		}
	}

	public static String isCollisionMisc(int code) {
		switch (code) {
		case Tile.OBJECTS_DIAMOND_SHARP:
		case Tile.OBJECTS_DIAMOND_SHARP_TOP:
		case Tile.OBJECTS_CHEST_OPEN:
		case Tile.OBJECTS_CHEST_CLOSED:
		case Tile.OBJECTS_ARMOR_STATUE:
		case Tile.OBJECTS_ARMOR_STATUE_LOWER:
		case Tile.OBJECTS_ARMOR_STATUE_UPPER:
		case Tile.OBJECTS_GRID_WHITE_UPPER:
		case Tile.OBJECTS_GRID_WHITE_LOWER:
		case Tile.OBJECTS_GRID_BLACK_UPPER:
		case Tile.OBJECTS_GRID_BLACK_LOWER:
		case Tile.OBJECTS_SPEARS_IN_BOX_UPPER:
		case Tile.OBJECTS_SPEARS_IN_BOX_LOWER:
		case Tile.OBJECTS_STONE_FIRE1:
		case Tile.OBJECTS_STONE_FIRE2:
		case Tile.OBJECTS_STONE_FIRE3:
		case Tile.OBJECTS_CHEST_SIDE_UPPER:
		case Tile.OBJECTS_CHEST_SIDE_LOWER:
		case Tile.OBJECTS_BUNKBED_TOPLEFT:
		case Tile.OBJECTS_BUNKBED_TOPRIGHT:
		case Tile.OBJECTS_BUNKBED_BOTTOMLEFT:
		case Tile.OBJECTS_BUNKBED_BOTTOMRIGHT:
		case Tile.OBJECTS_BOX_EMPTY:
		case Tile.OBJECTS_BOX_SWORDS:
		case Tile.OBJECTS_SHELF_HELMET_LEFT:
		case Tile.OBJECTS_SHELF_HELMET_RIGHT:
		case Tile.OBJECTS_SHELF_ARMOR_LEFT:
		case Tile.OBJECTS_SHELF_ARMOR_RIGHT:
		case Tile.OBJECTS_FIREPLACE_UPPER:
		case Tile.OBJECTS_FIREPLACE_MIDDLE:
		case Tile.OBJECTS_FIREPLACE_LOWER:
		case Tile.OBJECTS_ALTER_TOPLEFT:
		case Tile.OBJECTS_ALTER_TOPMIDDLE:
		case Tile.OBJECTS_ALTER_TOPRIGHT:
		case Tile.OBJECTS_ALTER_BOTTOMLEFT:
		case Tile.OBJECTS_ALTER_BOTTOMMIDDLE:
		case Tile.OBJECTS_ALTER_BOTTOMRIGHT:
		case Tile.OBJECTS_CROSS_ON_STICK_TOP:
		case Tile.OBJECTS_CANDLE_ON_STICK_TOP:
		case Tile.OBJECTS_STICK_BOTTOM:
		case Tile.OBJECTS_PILLAR_STATUE_TOP:
		case Tile.OBJECTS_PILLAR_TOP:
		case Tile.OBJECTS_PILLAR_BOTTOM:
			return Tile.OBJECTS_IMG_PATH + code;
		case Tile.WALL_STONE_BLOCK_LOWER:
		case Tile.WALL_STONE_BLOCK_UPPER:
			return Tile.WALL_IMG_PATH + code;
		case Tile.INTERIOR_TRAP_DOOR_UP:
		case Tile.INTERIOR_TRAP_DOOR_WOOD_UPPER:
		case Tile.INTERIOR_TRAP_DOOR_WOOD_MIDDLE:
		case Tile.INTERIOR_TRAP_DOOR_WOOD_LOWER:
		case Tile.INTERIOR_TRAP_DOOR_GOLDEN_UPPER:
		case Tile.INTERIOR_TRAP_DOOR_GOLDEN_MIDDLE:
		case Tile.INTERIOR_TRAP_DOOR_GOLDEN_LOWER:
		case Tile.INTERIOR_TRAP_DOOR_SILVER_UPPER:
		case Tile.INTERIOR_TRAP_DOOR_SILVER_MIDDLE:
		case Tile.INTERIOR_TRAP_DOOR_SILVER_LOWER:
		case Tile.INTERIOR_CURTAIN_RED_UPPER:
		case Tile.INTERIOR_CURTAIN_RED_LOWER:
		case Tile.INTERIOR_CLOSET_UPPER:
		case Tile.INTERIOR_CLOSET_LOWER:
		case Tile.INTERIOR_BOOKSHELF_UPPER:
		case Tile.INTERIOR_BOOKSHELF_LOWER:
		case Tile.INTERIOR_CUPBOARD_UPPER:
		case Tile.INTERIOR_CUPBOARD_LOWER:
		case Tile.INTERIOR_CLOSET1_UPPER:
		case Tile.INTERIOR_CLOSET1_LOWER:
		case Tile.INTERIOR_CLOSET2_UPPER:
		case Tile.INTERIOR_CLOSET2_LOWER:
		case Tile.INTERIOR_CLOSET2_UPPER_SHADOW:
		case Tile.INTERIOR_BOOKSHELF1_UPPER_FLOWER:
		case Tile.INTERIOR_BOOKSHELF1_UPPER:
		case Tile.INTERIOR_BOOKSHELF1_LOWER:
		case Tile.INTERIOR_CUPBOARD1_UPPER_THINGS:
		case Tile.INTERIOR_CUPBOARD1_LOWER:
		case Tile.INTERIOR_BED1_UPPER:
		case Tile.INTERIOR_BED1_MIDDLE:
		case Tile.INTERIOR_BED1_LOWER:
		case Tile.INTERIOR_BED2_UPPER:
		case Tile.INTERIOR_BED2_MIDDLE:
		case Tile.INTERIOR_BED2_LOWER:
		case Tile.INTERIOR_BED3_UPPER:
		case Tile.INTERIOR_BED3_MIDDLE:
		case Tile.INTERIOR_BED3_LOWER:
		case Tile.INTERIOR_BED4_UPPER:
		case Tile.INTERIOR_BED4_MIDDLE:
		case Tile.INTERIOR_BED4_LOWER:
		case Tile.INTERIOR_CLOSET_SIDEWAYS_UPPER:
		case Tile.INTERIOR_CLOSET_SIDEWAYS_MIDDLE:
		case Tile.INTERIOR_CLOSET_SIDEWAYS_LOWER:
		case Tile.INTERIOR_SLEEPING_BAGS:
		case Tile.INTERIOR_CUPBOARD2_UPPER:
		case Tile.INTERIOR_CUPBOARD2_LOWER:
		case Tile.INTERIOR_TABLE_SMALL:
		case Tile.INTERIOR_CHAIR_RED_FRONT:
		case Tile.INTERIOR_CHAIR_RED_BACK:
		case Tile.INTERIOR_CHAIR_RED_RIGHT:
		case Tile.INTERIOR_CHAIR_RED_LEFT:
		case Tile.INTERIOR_CHAIR_WHITE_UPPER:
		case Tile.INTERIOR_CHAIR_WHITE_LOWER:
		case Tile.INTERIOR_PILLOW:
		case Tile.INTERIOR_PILLOWS:
		case Tile.INTERIOR_TABLE_SMALL1:
		case Tile.INTERIOR_STOL:
		case Tile.INTERIOR_TABLE_SMALL_WATER:
		case Tile.INTERIOR_SHELF_BOOKS:
		case Tile.INTERIOR_SHELF_BOTTLES:
		case Tile.INTERIOR_CHAIR_RED_RSIDEWAYS_UPPER:
		case Tile.INTERIOR_CHAIR_RED_RSIDEWAYS_MIDDLE:
		case Tile.INTERIOR_CHAIR_RED_RSIDEWAYS_LOWER:
		case Tile.INTERIOR_CHAIR_RED_LSIDEWAYS_UPPER:
		case Tile.INTERIOR_CHAIR_RED_LSIDEWAYS_MIDDLE:
		case Tile.INTERIOR_CHAIR_RED_LSIDEWAYS_LOWER:
		case Tile.INTERIOR_BENCH_RSIDEWAYS_UPPER:
		case Tile.INTERIOR_BENCH_RSIDEWAYS_MIDDLE:
		case Tile.INTERIOR_BENCH_RSIDEWAYS_LOWER:
		case Tile.INTERIOR_BENCH_LEFT:
		case Tile.INTERIOR_BENCH_MIDDLE:
		case Tile.INTERIOR_BENCH_RIGHT:
			return Tile.INTERIOR_IMG_PATH + code;
		default:
			return "";
		}
	}

	public static String isMisc(int code) {
		switch (code) {
		case Tile.MISC_DAVID_STAR:
		case Tile.MISC_BOWS:
		case Tile.MISC_SWORDS:
		case Tile.MISC_SHIELD:
		case Tile.MISC_BED_FLOOR_LOWER:
		case Tile.MISC_BED_FLOOR_UPPER:
		case Tile.MISC_CIRCLE_RUG:
		case Tile.MISC_WALL_CRACK:
		case Tile.MISC_LONG_FLAG_UPPER:
		case Tile.MISC_LONG_FLAG_LOWER:
		case Tile.MISC_RED_FLAG:
		case Tile.MISC_BED_FLOOR_PILLOW:
		case Tile.MISC_DOCUMENTS:
		case Tile.MISC_MAP:
		case Tile.MISC_AXE:
		case Tile.MISC_ROUND_SHIELD:
		case Tile.MISC_ROPES:
		case Tile.MISC_ROPE:
		case Tile.MISC_SAND_SACKS:
		case Tile.MISC_STONE_TABLET:
		case Tile.MISC_SCYTHES:
			return Tile.MISC_IMG_PATH + code;
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_NORTH:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_NORTH_END:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_WEST:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_WEST_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_WEST_END:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_SOUTH:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_SOUTH_END:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_EAST:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_EAST_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_STAIR_EAST_END:
			return Tile.OUTDOORS_IMG_PATH + code;
		default:
			return "";
		}
	}

	public static String isMoveable(int code) {
		switch (code) {
		case Tile.OBJECTS_BOX:
		case Tile.OBJECTS_BOX_EMPTY:
		case Tile.OBJECTS_BOX_SWORDS:
			return Tile.OBJECTS_IMG_PATH + code;
		default:
			return "";
		}
	}

	public static String isTopLayer(int code) {
		switch (code) {
		case Tile.OBJECTS_PILLAR_TOP:
			return Tile.OBJECTS_IMG_PATH + code;
		default:
			return "";
		}
	}
	
	public static boolean isNotCollision(int code) {
		switch (code) {
		case Tile.OBJECTS_CHEST_OPEN:
		case Tile.OBJECTS_CHEST_CLOSED:
		case Tile.OBJECTS_ARMOR_STATUE:
		case Tile.OBJECTS_ARMOR_STATUE_LOWER:
		case Tile.OBJECTS_ARMOR_STATUE_UPPER:
		case Tile.WALL_STONE_BLOCK_LOWER:
		case Tile.WALL_STONE_BLOCK_UPPER:
		case Tile.OBJECTS_DIAMOND_SHARP:
		case Tile.OBJECTS_DIAMOND_SHARP_TOP:
		case Tile.OBJECTS_GRID_WHITE_UPPER:
		case Tile.OBJECTS_GRID_WHITE_LOWER:
		case Tile.OBJECTS_GRID_BLACK_UPPER:
		case Tile.OBJECTS_GRID_BLACK_LOWER:
		case Tile.OBJECTS_SPEARS_IN_BOX_UPPER:
		case Tile.OBJECTS_SPEARS_IN_BOX_LOWER:
		case Tile.OBJECTS_STONE_FIRE1:
		case Tile.OBJECTS_STONE_FIRE2:
		case Tile.OBJECTS_STONE_FIRE3:
		case Tile.OBJECTS_CHEST_SIDE_UPPER:
		case Tile.OBJECTS_CHEST_SIDE_LOWER:
		case Tile.OBJECTS_BUNKBED_TOPLEFT:
		case Tile.OBJECTS_BUNKBED_TOPRIGHT:
		case Tile.OBJECTS_BUNKBED_BOTTOMLEFT:
		case Tile.OBJECTS_BUNKBED_BOTTOMRIGHT:
		case Tile.OBJECTS_BOX_EMPTY:
		case Tile.OBJECTS_BOX_SWORDS:
		case Tile.OBJECTS_SHELF_HELMET_LEFT:
		case Tile.OBJECTS_SHELF_HELMET_RIGHT:
		case Tile.OBJECTS_SHELF_ARMOR_LEFT:
		case Tile.OBJECTS_SHELF_ARMOR_RIGHT:
		case Tile.OBJECTS_FIREPLACE_UPPER:
		case Tile.OBJECTS_FIREPLACE_MIDDLE:
		case Tile.OBJECTS_FIREPLACE_LOWER:
		case Tile.OBJECTS_ALTER_TOPLEFT:
		case Tile.OBJECTS_ALTER_TOPMIDDLE:
		case Tile.OBJECTS_ALTER_TOPRIGHT:
		case Tile.OBJECTS_ALTER_BOTTOMLEFT:
		case Tile.OBJECTS_ALTER_BOTTOMMIDDLE:
		case Tile.OBJECTS_ALTER_BOTTOMRIGHT:
		case Tile.OBJECTS_CROSS_ON_STICK_TOP:
		case Tile.OBJECTS_CANDLE_ON_STICK_TOP:
		case Tile.OBJECTS_STICK_BOTTOM:
		case Tile.OBJECTS_PILLAR_STATUE_TOP:
		case Tile.OBJECTS_PILLAR_TOP:
		case Tile.OBJECTS_PILLAR_BOTTOM:
		case Tile.INTERIOR_TRAP_DOOR_UP:
		case Tile.INTERIOR_TRAP_DOOR_WOOD_UPPER:
		case Tile.INTERIOR_TRAP_DOOR_GOLDEN_UPPER:
		case Tile.INTERIOR_TRAP_DOOR_SILVER_UPPER:
		case Tile.INTERIOR_CURTAIN_RED_UPPER:
		case Tile.INTERIOR_CLOSET_UPPER:
		case Tile.INTERIOR_CLOSET_LOWER:
		case Tile.INTERIOR_BOOKSHELF_UPPER:
		case Tile.INTERIOR_BOOKSHELF_LOWER:
		case Tile.INTERIOR_CUPBOARD_UPPER:
		case Tile.INTERIOR_CUPBOARD_LOWER:
		case Tile.INTERIOR_CLOSET1_UPPER:
		case Tile.INTERIOR_CLOSET1_LOWER:
		case Tile.INTERIOR_CLOSET2_UPPER:
		case Tile.INTERIOR_CLOSET2_LOWER:
		case Tile.INTERIOR_CLOSET2_UPPER_SHADOW:
		case Tile.INTERIOR_BOOKSHELF1_UPPER_FLOWER:
		case Tile.INTERIOR_BOOKSHELF1_UPPER:
		case Tile.INTERIOR_BOOKSHELF1_LOWER:
		case Tile.INTERIOR_CUPBOARD1_UPPER_THINGS:
		case Tile.INTERIOR_CUPBOARD1_LOWER:
		case Tile.INTERIOR_BED1_UPPER:
		case Tile.INTERIOR_BED1_MIDDLE:
		case Tile.INTERIOR_BED1_LOWER:
		case Tile.INTERIOR_BED2_UPPER:
		//case Tile.INTERIOR_BED2_MIDDLE:
		case Tile.INTERIOR_BED2_LOWER:
		case Tile.INTERIOR_BED3_UPPER:
		case Tile.INTERIOR_BED3_MIDDLE:
		case Tile.INTERIOR_BED3_LOWER:
		case Tile.INTERIOR_BED4_UPPER:
		case Tile.INTERIOR_BED4_MIDDLE:
		case Tile.INTERIOR_BED4_LOWER:
		case Tile.INTERIOR_CLOSET_SIDEWAYS_UPPER:
		case Tile.INTERIOR_CLOSET_SIDEWAYS_MIDDLE:
		case Tile.INTERIOR_CLOSET_SIDEWAYS_LOWER:
		case Tile.INTERIOR_SLEEPING_BAGS:
		case Tile.INTERIOR_CUPBOARD2_UPPER:
		case Tile.INTERIOR_CUPBOARD2_LOWER:
		case Tile.INTERIOR_TABLE_SMALL:
		case Tile.INTERIOR_CHAIR_RED_FRONT:
		case Tile.INTERIOR_CHAIR_RED_BACK:
		case Tile.INTERIOR_CHAIR_RED_RIGHT:
		case Tile.INTERIOR_CHAIR_RED_LEFT:
		case Tile.INTERIOR_CHAIR_WHITE_UPPER:
		//case Tile.INTERIOR_CHAIR_WHITE_LOWER:
		case Tile.INTERIOR_PILLOW:
		case Tile.INTERIOR_PILLOWS:
		case Tile.INTERIOR_TABLE_SMALL1:
		case Tile.INTERIOR_STOL:
		case Tile.INTERIOR_TABLE_SMALL_WATER:
		case Tile.INTERIOR_SHELF_BOOKS:
		case Tile.INTERIOR_SHELF_BOTTLES:
		case Tile.INTERIOR_CHAIR_RED_RSIDEWAYS_UPPER:
		case Tile.INTERIOR_CHAIR_RED_RSIDEWAYS_MIDDLE:
		case Tile.INTERIOR_CHAIR_RED_RSIDEWAYS_LOWER:
		case Tile.INTERIOR_CHAIR_RED_LSIDEWAYS_UPPER:
		case Tile.INTERIOR_CHAIR_RED_LSIDEWAYS_MIDDLE:
		case Tile.INTERIOR_CHAIR_RED_LSIDEWAYS_LOWER:
		case Tile.INTERIOR_BENCH_RSIDEWAYS_UPPER:
		case Tile.INTERIOR_BENCH_RSIDEWAYS_MIDDLE:
		case Tile.INTERIOR_BENCH_RSIDEWAYS_LOWER:
		case Tile.INTERIOR_BENCH_LEFT:
		case Tile.INTERIOR_BENCH_MIDDLE:
		case Tile.INTERIOR_BENCH_RIGHT:
		case Tile.WALL_STONE:
		case Tile.WALL_STONE_CRACK:
		case Tile.WALL_CAVE_BOTTOM:
		case Tile.WALL_CAVE_BOTTOM_DARK:
		case Tile.WALL_CAVE_TOP:
		case Tile.WALL_CAVE_MIDDLE:
		case Tile.WALL_CAVE_BOTTOM_CRACK:
		case Tile.WALL_CAVE_DOOR_LEFT_UPPER:
		case Tile.WALL_CAVE_DOOR_RIGHT_UPPER:
		case Tile.WALL_CAVE_DOOR_UPPER:
		case Tile.WALL_LAVA_LEFT_LOW:
		case Tile.WALL_LAVA_LEFT_LOWER:
		case Tile.WALL_LAVA_LEFT_LOWEST:
		case Tile.WALL_LAVA_LEFT_MIDDLE:
		case Tile.WALL_LAVA_LEFT_UPPER:
		case Tile.WALL_LAVA_RIGHT_LOW:
		case Tile.WALL_LAVA_RIGHT_LOWER:
		case Tile.WALL_LAVA_RIGHT_LOWEST:
		case Tile.WALL_LAVA_RIGHT_MIDDLE:
		case Tile.WALL_LAVA_RIGHT_UPPER:
		case Tile.WALL_LAVA_LOW:
		case Tile.WALL_LAVA_LOWER:
		case Tile.WALL_LAVA_LOWEST:
		case Tile.WALL_LAVA_UPPER:
			// case Tile.WALL_CAVE_DOOR_LOWER:
			// case Tile.WALL_CAVE_DOOR_BOTTOM:
			// case Tile.WALL_CAVE_DOOR_LEFT:
			// case Tile.WALL_CAVE_DOOR_RIGHT:
		case Tile.OUTDOORS_FENCE_ALONE:
		case Tile.OUTDOORS_FENCE_END:
		case Tile.OUTDOORS_FENCE_CROSS:
		case Tile.OUTDOORS_FENCE_TOP_LEFT:
		case Tile.OUTDOORS_FENCE_TOP_RIGHT:
		case Tile.OUTDOORS_FENCE_BOTTOM_LEFT:
		case Tile.OUTDOORS_FENCE_BOTTOM_RIGHT:
		case Tile.OUTDOORS_FENCE_HORIZONTAL:
		case Tile.OUTDOORS_FENCE_VERTICAL:
		case Tile.OUTDOORS_FENCE_CROSS_LEFT:
		case Tile.OUTDOORS_FENCE_CROSS_RIGHT:
		case Tile.OUTDOORS_FENCE_CROSS_NORTH:
		case Tile.OUTDOORS_FENCE_CROSS_SOUTH:
		case Tile.OUTDOORS_FENCE_TOP_LEFT1:
		case Tile.OUTDOORS_FENCE_TOP_RIGHT1:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_TOP_RIGHT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_LEFT:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_MIDDLE:
		case Tile.OUTDOORS_STONE_PLATEAU_WALL_BOTTOM_RIGHT:
			return false;
		default:
			return true;
		}
	}
}
